#!/usr/bin/env python3
"""
Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full
list see the documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

from __future__ import annotations

import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "bases"))
sys.path.insert(0, str(project_root / "components"))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Ai-task Notify Hook"
copyright = "2025, User"
author = "User"
version = "1.0.0"
release = "1.0.0"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    # Core Sphinx extensions
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.ifconfig",
    # Third-party extensions
    "sphinx_rtd_theme",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**.ipynb_checkpoints",
]

# The language for content autogenerated by Sphinx.
language = "en"

# The master document (without file extension).
master_doc = "index"

# The default role used by default for inline text
default_role = "code"

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# A boolean that decides whether module names are prepended to all object names
modindex_common_prefix = ["ai_task_notify_hook."]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_rtd_theme"

# Theme options
html_theme_options = {
    "analytics_id": "",
    "analytics_anonymize_ip": False,
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "white",
    # Toc options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    "**": [
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
    ]
}

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"
pygments_dark_style = "monokai"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for autodoc ----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration

# This value selects if automatically documented members are sorted
# alphabetical (value 'alphabetical'), by member type (value 'groupwise')
# or by source order (value 'source'). The default is alphabetical.
autodoc_member_order = "bysource"

# This value is a list of autodoc directive flags that should be automatically
# applied to all autodoc directives.
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# This value controls how to represent typehints.
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"

# -- Options for autosummary ------------------------------------------------

# Boolean indicating whether to scan all found documents for autosummary
# directives, and to generate stub pages for each.
autosummary_generate = True

# If true, autosummary overwrites existing files by generated stub pages.
autosummary_generate_overwrite = False

# A dictionary mapping names to functions for autosummary generation.
autosummary_mock_imports = []

# -- Options for Napoleon (Google/NumPy docstring support) ------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#configuration

# True to parse Google style docstrings. False to disable support.
napoleon_google_docstring = True

# True to parse NumPy style docstrings. False to disable support.
napoleon_numpy_docstring = True

# True to include private members (like _private) with docstrings
# in the documentation. False to fall back to Sphinx's default behavior.
napoleon_include_private_with_doc = False

# True to include special members (like __special__) with docstrings
# in the documentation. False to fall back to Sphinx's default behavior.
napoleon_include_special_with_doc = True

# True to use the .. admonition:: directive for the Example and Examples
# sections. False to use the .. rubric:: directive instead.
napoleon_use_admonition_for_examples = False

# True to use the .. admonition:: directive for Notes sections.
# False to use the .. rubric:: directive instead.
napoleon_use_admonition_for_notes = False

# True to use the .. admonition:: directive for References sections.
# False to use the .. rubric:: directive instead.
napoleon_use_admonition_for_references = False

# True to use the :ivar: role for instance variables.
# False to use the .. attribute:: directive instead.
napoleon_use_ivar = False

# True to use a :param: role for each function parameter.
# False to use a single :parameters: field for all the parameters.
napoleon_use_param = True

# True to use a :keyword: role for each function keyword argument.
# False to use a single :keyword arguments: field for all the keyword arguments.
napoleon_use_keyword = True

# True to use the :rtype: role for the return type.
# False to output the return type inline with the description.
napoleon_use_rtype = True

# True to convert the type definitions in the docstrings as references.
# False to let the type definitions appear as-is.
napoleon_preprocess_types = True

# A mapping of strings to string, translating type names that are not otherwise
# translated by the type parsing regular expressions.
napoleon_type_aliases = {
    "array-like": ":term:`array-like <numpy:array_like>`",
    "array_like": ":term:`array-like <numpy:array_like>`",
}

# -- Options for intersphinx extension --------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#configuration

# This config value contains the locations and names of other projects that
# should be linked to in this documentation.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "structlog": ("https://www.structlog.org/en/stable/", None),
    "plyer": ("https://plyer.readthedocs.io/en/latest/", None),
}

# The maximum number of days to cache remote inventories.
intersphinx_cache_limit = 5

# The number of seconds for timeout.
intersphinx_timeout = None

# -- Options for MyST parser ------------------------------------------------
# https://myst-parser.readthedocs.io/en/latest/configuration.html

# Enable certain MyST syntax features
myst_enable_extensions = [
    "deflist",
    "tasklist",
    "colon_fence",
    "substitution",
    "attrs_inline",
]

# The URL scheme to use for cross-references to other MyST sites
myst_url_schemes = ["http", "https", "mailto"]

# -- Options for LaTeX output -----------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-latex-output

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    "papersize": "a4paper",
    # The font size ('10pt', '11pt' or '12pt').
    "pointsize": "10pt",
    # Additional stuff for the LaTeX preamble.
    "preamble": "",
    # Latex figure (float) alignment
    "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "AI-Task-Notify-Hook.tex",
        "Ai-task Notify Hook Documentation",
        "User",
        "manual",
    ),
]

# -- Options for manual page output -----------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "AI-Task-Notify-Hook",
        "Ai-task Notify Hook Documentation",
        [author],
        1,
    )
]

# -- Options for Texinfo output ---------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-texinfo-output

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Ai-taskNotifyHook",
        "Ai-task Notify Hook Documentation",
        author,
        "Ai-taskNotifyHook",
        "Simple Windows notification tool for Claude Code hooks.",
        "Miscellaneous",
    ),
]

# -- Extension configuration -------------------------------------------------


def setup(app):
    """Sphinx application setup hook."""
    # Add custom CSS
    app.add_css_file("custom.css")
